/* export const metadata = {
    title: "Product page",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <div>Product navigation</div>
            <div>{children}</div>
        </>
    );
}
 */